server:
  port: 8082

spring:
  application:
    name: ride-service
  datasource:
    url: jdbc:postgresql://localhost:5434/cabsy_ride
    username: cabsy
    password: cabsy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

cabsy:
  kafka:
    topics:
      ride-requested: ride-requested
      ride-status-changed: ride-status-changed